<script setup>
import { computed, ref } from 'vue'
import { base, preview, token, usePoll } from '../api.js'
const emit=defineEmits(['settings'])
const list=value=>Array.isArray(value)?value:[]
const root=base.replace(/openclash$/,'router_node_health'),data=ref(null),selected=ref(''),search=ref(''),mode=ref('all'),error=ref(''),message=ref(''),busy=ref(false)
async function load(signal){if(preview)return;try{const r=await fetch(`${root}/status?${new URLSearchParams({node:selected.value})}`,{signal,cache:'no-store'});if(!r.ok)throw Error(`节点监控接口 ${r.status}`);data.value=await r.json();error.value=data.value.error||'';if(!selected.value&&data.value.nodes?.length){selected.value=data.value.nodes[0].name;await load(signal)}}catch(e){if(e.name!=='AbortError')error.value=e.message}}
usePoll(load,5000)
async function action(name,body={}){if(preview||busy.value)return;busy.value=true;try{const r=await fetch(`${root}/${name}`,{method:'POST',body:new URLSearchParams({...body,token})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||`操作失败 ${r.status}`);message.value=d.message;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
const labels={up:'正常',degraded:'首次失败',down:'持续故障',unknown:'未检测',removed:'已移除'}
const nodes=computed(()=>list(data.value?.nodes).filter(n=>(mode.value==='all'||n.status===mode.value)&&n.name.toLowerCase().includes(search.value.toLowerCase())))
const detail=computed(()=>data.value?.detail),summary=computed(()=>list(data.value?.nodes).find(n=>n.name===selected.value)?.summary||{})
const health=computed(()=>!data.value?.enabled?'尚未启用':data.value?.stale||error.value?'监控状态过期':data.value?.core_state!=='available'?'内核不可用 · 历史保留':'持续监控中')
const samples=computed(()=>list(detail.value?.samples)),maxY=computed(()=>Math.max(100,...samples.value.filter(s=>s[2]===1).map(s=>s[1]))*1.1)
const start=computed(()=>samples.value[0]?.[0]||0),end=computed(()=>Math.max(start.value+1,samples.value.at(-1)?.[0]||0))
const x=s=>40+(s[0]-start.value)/(end.value-start.value)*820,y=s=>190-s[1]/maxY.value*160
const paths=computed(()=>{const segments=[];let current=[];for(const s of samples.value){if(s[2]===1)current.push(`${x(s)},${y(s)}`);else if(current.length){segments.push(current.join(' '));current=[]}}if(current.length)segments.push(current.join(' '));return segments})
const hours=computed(()=>{const known=new Map(list(detail.value?.hours).map(h=>[h[0],h]));const latest=Math.floor((data.value?.timestamp||Date.now()/1000)/3600)*3600;return Array.from({length:168},(_,i)=>known.get(latest-(167-i)*3600)||[latest-(167-i)*3600,0,0,0,0,0])})
const num=n=>typeof n==='number'?`${Math.round(n)} ms`:'—',pct=n=>typeof n==='number'?`${n.toFixed(2)}%`:'—',time=t=>t?new Date(t*1000).toLocaleString('zh-CN',{hour12:false}):'—'
async function choose(name){selected.value=name;await load()}
</script>
<template>
 <p v-if="error" class="oc-error" role="alert">{{error}}</p><p v-if="message" class="oc-success" role="status">{{message}}</p>
 <section class="oc-hero"><div><span class="oc-eyebrow">节点历史 · 独立服务</span><h2>{{health}}</h2><p>HTTPS 经节点的实际请求耗时。连续两次失败标为故障，内核停用或监控失效标为未知；不会自动切换节点。</p></div><div class="oc-actions"><button @click="emit('settings')">监控设置</button><a :href="`${root}/export`" download>导出历史</a><button :disabled="busy||preview" @click="action('checkpoint')">保存检查点</button></div></section>
 <p class="oc-note">可用率按已完成探测计算，未检测不计入分母。短于检测间隔的故障可能遗漏。最近 {{data?.keep_samples||240}} 次记录＋7 天小时汇总；自动持久化每小时最多一次，意外掉电最多丢失一小时数据。</p>
 <p v-if="data?.capacity_limited" class="oc-notice">发现 {{data.discovered}} 个节点，已达到检测容量。当前只检测名称排序后的前 {{data.nodes.filter(n=>!n.removed).length}} 个；可在设置中调整，最大 64。</p>
 <div class="oc-health-layout"><section class="oc-card oc-health-list"><div class="oc-toolbar"><input v-model="search" type="search" aria-label="搜索监控节点" placeholder="搜索节点"><select v-model="mode" aria-label="筛选节点状态"><option value="all">所有状态</option><option v-for="(label,key) in labels" :value="key">{{label}}</option></select></div><div class="oc-health-rows"><button v-for="n in nodes" :key="n.name" :class="{active:selected===n.name}" @click="choose(n.name)"><div><strong>{{n.name}}</strong><small>{{n.type}} · {{time(n.checked)}}</small></div><span :class="`oc-health-state ${n.status}`">{{labels[n.status]}}</span><span>{{pct(n.summary.availability)}}</span><small>P95 {{num(n.summary.p95)}}</small></button><p v-if="!nodes.length" class="oc-empty">启用监控后自动发现内核中的具体节点。策略组与 DIRECT / REJECT 不计为节点。</p></div></section>
 <section class="oc-card oc-health-detail"><template v-if="detail"><div class="oc-editor-head"><div><h3>{{detail.name}}</h3><small>{{detail.type}} · {{labels[detail.status]}}</small></div><button :disabled="busy||preview||detail.removed||!data.enabled" @click="action('probe',{node:detail.name})">立即检测</button></div>
 <div class="oc-health-metrics"><div><small>探测可用率</small><strong>{{pct(summary.availability)}}</strong></div><div><small>中位延迟</small><strong>{{num(summary.median)}}</strong></div><div><small>P95 延迟</small><strong>{{num(summary.p95)}}</strong></div><div><small>延迟波动</small><strong>{{num(summary.jitter)}}</strong></div></div>
 <figure class="oc-health-chart"><figcaption>最近探测延迟 <small>波动为相邻成功探测耗时之差的平均绝对值</small></figcaption><svg viewBox="0 0 900 225" role="img" aria-label="节点历史延迟曲线"><line x1="40" y1="190" x2="860" y2="190" stroke="#cbd5e1"/><line x1="40" y1="30" x2="860" y2="30" stroke="#e2e8f0"/><text x="2" y="35">{{Math.round(maxY)}}ms</text><text x="15" y="194">0</text><polyline v-for="(p,i) in paths" :key="i" :points="p" fill="none" stroke="#2563eb" stroke-width="2.5"/><circle v-for="s in samples" :cx="x(s)" :cy="s[2]===1?y(s):205" :r="s[2]===1?2.3:3" :fill="s[2]===1?'#2563eb':s[2]===0?'#dc2626':'#94a3b8'"><title>{{time(s[0])}} · {{s[2]===1?num(s[1]):s[2]===0?'检测失败':'未检测'}}</title></circle><text x="40" y="222">{{time(start)}}</text><text x="860" y="222" text-anchor="end">{{time(end)}}</text></svg></figure>
 <div class="oc-health-hour"><strong>7 天小时可用率</strong><div><span v-for="h in hours" :style="{background:h[1]+h[2]===0?'#cbd5e1':h[2]===0?'#10b981':h[1]===0?'#ef4444':'#f59e0b'}" :title="`${time(h[0])} · ${pct(h[1]+h[2]>0?h[1]/(h[1]+h[2])*100:null)} · 成功 ${h[1]} / 失败 ${h[2]} / 未检测 ${h[5]}`"></span></div><small>绿：全部成功　黄：部分失败　红：全部失败　灰：没有有效探测；空白时段无记录。</small></div>
 <dl class="oc-health-info"><dt>累计成功 / 失败 / 未检测</dt><dd>{{detail.ok}} / {{detail.failed}} / {{detail.unknown}}</dd><dt>恢复次数 / 最近故障持续</dt><dd>{{detail.recoveries}} / {{detail.last_outage!=null?detail.last_outage+' 秒':'—'}}</dd><dt>最近目标</dt><dd>{{detail.last_target||'—'}}</dd><dt>最近错误</dt><dd>{{detail.last_error||'无'}}</dd></dl>
 <details open class="oc-health-events"><summary>状态变化记录</summary><div v-for="(e,i) in [...list(detail.events)].reverse()" :key="i"><time>{{time(e.time)}}</time><span>{{labels[e.from]}} → {{labels[e.to]}}</span><small>{{e.reason}}</small></div></details>
 </template><div v-else class="oc-empty">选择节点查看延迟曲线、可用率和故障恢复记录</div></section></div>
</template>
<style>
.oc-health-layout{display:grid;grid-template-columns:minmax(260px,34%) minmax(0,1fr);gap:18px}.oc-health-layout .oc-card{min-width:0}.oc-health-list .oc-toolbar{flex-wrap:wrap}.oc-health-list input{min-width:0;width:100%}.oc-health-rows{max-height:620px;overflow:auto}.oc-health-rows>button{width:100%;display:grid;grid-template-columns:1fr auto;gap:8px;text-align:left;border:0!important;border-bottom:1px solid #edf0f5!important;border-radius:0!important;padding:14px!important}.oc-health-rows button.active{background:#eff6ff!important}.oc-health-rows strong{display:block;overflow-wrap:anywhere}.oc-health-rows small{font-size:10px;color:#8290a5;display:block;margin-top:5px}.oc-health-state{font-size:11px;color:#64748b}.oc-health-state.up{color:#059669}.oc-health-state.down{color:#dc2626}.oc-health-state.degraded{color:#d97706}.oc-health-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:22px 0}.oc-health-metrics small{font-size:11px;color:#8290a5}.oc-health-metrics strong{display:block;font-size:20px;margin-top:6px}.oc-health-chart{margin:25px 0}.oc-health-chart figcaption{font-size:12px}.oc-health-chart small{display:block;font-size:10px;color:#8290a5;margin-top:6px}.oc-health-chart svg{width:100%;margin-top:15px}.oc-health-chart text{font-size:11px;fill:#8290a5}.oc-health-hour{font-size:12px}.oc-health-hour>div{display:flex;flex-wrap:wrap;gap:4px;margin:12px 0}.oc-health-hour span{width:12px;height:16px;border-radius:2px}.oc-health-hour small{font-size:10px;color:#8290a5}.oc-health-info{display:grid;grid-template-columns:150px 1fr;gap:10px;font-size:11px;margin-top:22px}.oc-health-info dd{margin:0;overflow-wrap:anywhere}.oc-health-info dt{color:#8290a5}.oc-health-events{font-size:12px;margin-top:25px}.oc-health-events>div{display:grid;grid-template-columns:1fr 1fr;gap:8px;border-bottom:1px solid #edf0f5;padding:10px 0;font-size:11px}.oc-health-events small{color:#8290a5}.oc-health-events{max-height:250px;overflow:auto}
@media(max-width:1050px){.oc-health-layout{grid-template-columns:1fr}.oc-health-rows{max-height:300px}.oc-health-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.oc-health-info{grid-template-columns:1fr}.oc-health-info dd{margin-bottom:8px}.oc-health-detail .oc-editor-head{align-items:start;flex-wrap:wrap}.oc-health-detail h3{overflow-wrap:anywhere}}
</style>
