<script setup>
import { computed, ref, defineAsyncComponent } from 'vue'
import { request, usePoll, preview, base, token } from '../api.js'
const emit=defineEmits(['settings','navigate'])
const OverviewTools=defineAsyncComponent(()=>import('../widgets/OverviewTools.vue'))
const status=ref(null),metrics=ref(null),configuration=ref(null),dashboardUrl=ref(''),error=ref(''),busy=ref(false),points=ref([])
const providers=[['ipify','IPify'],['ipsb','IP.sb'],['pcol','太平洋网络'],['ipip','IPIP']]
const exits=ref(Object.fromEntries(providers.map(([id])=>[id,{state:'未查询'}]))),checking=ref(false)
function parseExit(content){try{const d=JSON.parse(content);return {ip:d.ip||d.query||'未返回 IP',detail:[d.country,d.region,d.city,d.isp||d.organization,d.addr].filter(Boolean).join(' · ')}}catch{const ip=content.match(/(?:\d{1,3}\.){3}\d{1,3}/)?.[0];return {ip:ip||'未识别地址',detail:content.replace(/<[^>]*>/g,'').trim().slice(0,200)}}}
async function checkExit(){if(checking.value||preview)return;checking.value=true;await Promise.allSettled(providers.map(async([id])=>{exits.value[id]={state:'查询中'};try{const d=await request('modern_myip',{provider:id});exits.value[id]={state:'已查询',...parseExit(d.content)}}catch(e){exits.value[id]={state:'查询失败',detail:e.message}}}));checking.value=false}
usePoll(async signal=>{const results=await Promise.allSettled([request('status',{},signal),request('modern_metrics',{},signal)]);if(signal.aborted)return;for(let i=0;i<results.length;i++){const r=results[i];if(r.status==='fulfilled'){if(i===0)status.value=r.value;else{metrics.value=r.value;points.value=[...points.value,{time:Date.now(),up:r.value.upload_rate,down:r.value.download_rate}].slice(-60)}}else error.value=r.reason.message}if(results.every(r=>r.status==='fulfilled'))error.value=''},5000)
usePoll(async signal=>{const result=await Promise.allSettled([request('config_name',{},signal),request('modern_dashboard_info',{},signal)]);if(signal.aborted)return;if(result[0].status==='fulfilled')configuration.value=result[0].value;if(result[1].status==='fulfilled')dashboardUrl.value=result[1].value.url},30000)
const mode=computed(()=>({rule:'规则分流',global:'全局代理',direct:'全部直连'})[status.value?.rule_mode]||status.value?.rule_mode||'—')
const running=computed(()=>status.value?.clash?'OpenClash 运行中':metrics.value?.core_available?'独立内核运行中':'服务已停止')
const configName=computed(()=>configuration.value?.config_path?.split('/').pop()||'未读取配置')
const bytes=value=>value==null?'—':value>=1073741824?(value/1073741824).toFixed(2)+' GB':value>=1048576?(value/1048576).toFixed(1)+' MB':value>=1024?(value/1024).toFixed(1)+' KB':Math.round(value)+' B'
const memoryPercent=computed(()=>metrics.value?.memory_total?Math.round((1-metrics.value.memory_available/metrics.value.memory_total)*100):0)
const graphMax=computed(()=>Math.max(1024,...points.value.flatMap(p=>[p.up||0,p.down||0])))
function lines(key){const segments=[];let segment=[];for(const [i,p] of points.value.entries()){if(p[key]==null){if(segment.length)segments.push(segment.join(' '));segment=[]}else segment.push(`${10+i*780/59},${130-p[key]/graphMax.value*110}`)}if(segment.length)segments.push(segment.join(' '));return segments}
async function action(name){if(preview||busy.value)return;busy.value=true;try{const r=await fetch(`${base}/modern_action`,{method:'POST',body:new URLSearchParams({action:name,token})});if(!r.ok)throw Error(`操作失败 (${r.status})`);status.value=await request('status')}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template>
 <p v-if="error" class="oc-error" role="alert">{{error}}</p>
 <div class="oc-home-top"><section class="oc-card oc-service-card"><header><div><span class="oc-eyebrow">运行状态</span><h2><span class="oc-dot" :class="{offline:!metrics?.core_available}"></span>{{running}}</h2></div><span class="oc-badge">{{status?.core_type==='Meta'?'Mihomo':status?.core_type||'Mihomo'}}</span></header><p>{{status?.run_mode||'正在读取运行模式'}} · {{mode}}</p><div class="oc-actions"><button :disabled="preview||busy||!status" @click="action(status.clash?'stop':'start')">{{status?.clash?'停止 OpenClash':'启动 OpenClash'}}</button><button :disabled="preview||busy||!status" @click="action('restart')">重启服务</button><button @click="emit('settings')">管理设置</button></div></section>
 <section class="oc-card oc-config-summary"><span class="oc-eyebrow">当前配置</span><h3>{{configName}}</h3><p class="oc-muted">{{configuration?.config_path||'—'}}</p><div class="oc-actions"><button @click="emit('navigate','files')">配置与文件</button><button class="primary" @click="emit('navigate','dashboard')">打开 Dashboard</button><a v-if="dashboardUrl" :href="dashboardUrl" target="_blank" rel="noreferrer">独立窗口 ↗</a></div></section></div>
 <div class="oc-home-metrics"><article><span>上传速率</span><strong>{{bytes(metrics?.upload_rate)}}<small>/s</small></strong></article><article><span>下载速率</span><strong>{{bytes(metrics?.download_rate)}}<small>/s</small></strong></article><article><span>累计上传</span><strong>{{bytes(metrics?.upload_total)}}</strong></article><article><span>累计下载</span><strong>{{bytes(metrics?.download_total)}}</strong></article><article><span>活动连接</span><strong>{{metrics?.connections??'—'}}</strong></article><article><span>系统内存</span><strong>{{metrics?memoryPercent:'—'}}<small>%</small></strong></article><article><span>系统 CPU</span><strong>{{metrics?.cpu_percent==null?'—':metrics.cpu_percent.toFixed(1)}}<small>%</small></strong></article><article><span>系统负载（1 分钟）</span><strong>{{metrics?.load??'—'}}</strong></article></div>
 <div class="oc-home-charts"><article class="oc-card"><header class="oc-card-heading"><h3>实时代理流量</h3><div class="oc-chart-legend"><span>● 上传</span><span>● 下载</span></div></header><p class="oc-muted">最近 5 分钟 · 每 5 秒采样 · 内核累计计数差值</p><svg class="oc-traffic-chart" viewBox="0 0 800 155" role="img" aria-label="实时上传与下载速率"><path d="M10 20H790 M10 75H790 M10 130H790" fill="none" stroke="#edf1f7"/><polyline v-for="(segment,index) in lines('down')" :key="'down'+index" :points="segment" fill="none" stroke="#39b3a0" stroke-width="2.5"/><polyline v-for="(segment,index) in lines('up')" :key="'up'+index" :points="segment" fill="none" stroke="#3978ed" stroke-width="2.5"/></svg><div class="oc-chart-axis"><span>{{bytes(graphMax)}}/s</span><span>{{metrics?.core_available?'计数自内核启动累计；内核重启后重置':'内核 API 不可用，流量保持未知'}}</span></div></article><article class="oc-card"><h3>系统资源</h3><div class="oc-resource-meter"><span>CPU 占用</span><strong>{{metrics?.cpu_percent==null?'等待第二次采样':metrics.cpu_percent.toFixed(1)+'%'}}</strong><meter min="0" max="100" :value="metrics?.cpu_percent||0"></meter></div><div class="oc-resource-meter"><span>内存占用</span><strong>{{bytes(metrics?metrics.memory_total-metrics.memory_available:null)}} / {{bytes(metrics?.memory_total)}}</strong><meter min="0" max="100" :value="memoryPercent"></meter></div><p class="oc-muted">系统指标来自路由器；流量指标只覆盖内核连接。</p><div class="oc-actions"><button @click="emit('navigate','health')">节点历史</button><button @click="emit('navigate','security')">流量隐私</button></div></article></div>
 <OverviewTools :status="status">
 <section class="oc-card oc-exit-section"><header class="oc-card-heading"><div><h3>路由器出口查询</h3><p>四个服务同时查询，分别展示本次路由器请求的出口。</p></div><button :disabled="checking||preview" @click="checkExit">{{checking?'正在查询四个服务…':'查询全部出口'}}</button></header><div class="oc-exit-grid"><article v-for="[id,name] in providers"><header><strong>{{name}}</strong><small :class="{failure:exits[id].state==='查询失败'}">{{exits[id].state}}</small></header><b>{{exits[id].ip||'—'}}</b><p>{{exits[id].detail||'等待手动查询'}}</p></article></div><small class="oc-muted">查询服务会看到该请求的出口地址；结果不能代表所有客户端或所有目标的实际路径。</small></section></OverviewTools>
</template>
