<script setup>
import {computed,ref,watch,nextTick,onBeforeUnmount} from 'vue'
import {base,preview,token,usePoll} from '../api.js'
const emit=defineEmits(['settings']),root=base.replace(/openclash$/,'router_privacy')
const data=ref(null),error=ref(''),message=ref(''),busy=ref(false),search=ref(''),filter=ref('all'),region=ref('all'),protocol=ref(''),page=ref(1),selected=ref(null),basis=ref('count')
watch(selected,async value=>{if(value){await nextTick();document.querySelector('.oc-privacy-detail')?.focus()}})
const list=v=>Array.isArray(v)?v:[],number=v=>Number(v)||0,bytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MiB':n>=1024?(n/1024).toFixed(1)+' KiB':Math.round(n||0)+' B'
let requestId=0
async function load(signal){if(preview)return;const id=++requestId;try{const r=await fetch(`${root}/status?${new URLSearchParams({search:search.value,filter:filter.value,region:region.value,protocol:protocol.value,page:page.value})}`,{signal,cache:'no-store'});if(!r.ok)throw Error(`监控接口 ${r.status}`);const d=await r.json();if(d.error)throw Error(d.error);if(id===requestId){data.value=d;error.value=''}}catch(e){if(e.name!=='AbortError'&&id===requestId)error.value=e.message}}
usePoll(load,5000)
watch([filter,region,protocol],()=>{page.value=1;load()})
let searchTimer;watch(search,()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page.value=1;load()},250)})
onBeforeUnmount(()=>{clearTimeout(searchTimer);requestId++})
const monitor=computed(()=>data.value?.monitor||{}),dns=computed(()=>data.value?.dns||{}),dashboard=computed(()=>data.value?.dashboard||{})
const live=computed(()=>!!data.value&&!data.value.stale&&monitor.value.enabled&&dashboard.value.available&&!error.value)
const status=computed(()=>data.value?.stale||error.value?'状态过期 · 安全性待确认':!dns.value.enabled?'未开启':!dns.value.firewall_installed?'保护规则未生效':!dns.value.resolver_running||dns.value.health?.available===false?'解析不可用 · 禁止明文回退':dns.value.health?.available?'独立保护运行中':'规则已生效 · 解析待验证')
const encryptionLabels={encrypted:'加密迹象 · TLS',plaintext:'确认明文',unknown:'加密性未知'},colors={encrypted:'#14b8a6',plaintext:'#f97366',unknown:'#b2bfd3'}
const portions=computed(()=>Object.entries(encryptionLabels).map(([key,label])=>({key,label,value:number(dashboard.value.encryption?.[key]?.[basis.value]),color:colors[key]})))
const total=computed(()=>portions.value.reduce((n,p)=>n+p.value,0)),ratio=key=>live.value&&total.value?((portions.value.find(p=>p.key===key)?.value||0)/total.value*100).toFixed(1)+'%':'—'
const donut=computed(()=>{if(!live.value||!total.value)return '#e6ebf3';let from=0;return 'conic-gradient('+portions.value.map(p=>{const to=from+p.value/total.value*100;const text=`${p.color} ${from}% ${to}%`;from=to;return text}).join(',')+')'})
const metric=v=>live.value?number(v):'—'
const classified=computed(()=>number(dashboard.value.geography?.domestic?.count)+number(dashboard.value.geography?.overseas?.count))
const regionMetric=v=>live.value?(classified.value?number(v):'未知'):'—'
const routes={ 'direct-observed':'WAN 实测直连','direct-reported':'内核报告直连','proxy-reported':'经过节点','blocked-reported':'内核拦截','wan-egress-unattributed':'外联用途未关联','conflicting-evidence':'路径证据冲突',unknown:'路径未知'}
const regions={domestic:'国内 · Clash 判定',overseas:'国外 · Clash 判定',unknown:'归类未知'}
const protocols={'tls-clienthello':'TLS / HTTPS 握手','plaintext-http':'明文 HTTP','plaintext-dns':'明文 DNS','quic-uninspected':'QUIC · 加密性未验证','encrypted-dns-candidate':'疑似加密 DNS','tls-incomplete':'不完整 TLS 握手','tcp-unknown':'未识别 TCP','udp-unknown':'未识别 UDP','not-observed':'未捕获握手',other:'其他协议'}
const protocolRows=computed(()=>Object.entries(dashboard.value.protocols||{}).map(([key,v])=>({key,label:protocols[key]||key,count:number(v.count),value:number(v[basis.value]),bytes:number(v.bytes)})).sort((a,b)=>b.value-a.value))
const maxProtocol=computed(()=>Math.max(1,...protocolRows.value.map(p=>p.value)))
const geoRows=computed(()=>Object.entries(regions).map(([key,label])=>({key,label,...dashboard.value.geography?.[key]})))
const risks=computed(()=>[['dns','明文 DNS 离开 WAN',dashboard.value.dns?.wan_plaintext,'查询域名可被上游网络读取'],['overseas-sni','国外站点 SNI 可见',dashboard.value.sni?.overseas,'TLS 加密正文，握手域名仍可见'],['overseas-direct','国外站点直连',dashboard.value.risks?.overseas_direct,'检查命中规则与实际路径'],['plaintext','明文 HTTP 外联',dashboard.value.risks?.plaintext_http,'请求内容未受 TLS 保护']])
function focus(kind){filter.value=kind;protocol.value='';region.value='all';document.getElementById('privacy-connections')?.scrollIntoView({behavior:'smooth',block:'start'})}
const trend=computed(()=>list(dashboard.value.trend).filter(p=>p.time>=(data.value?.timestamp||0)-300)),maxTrend=computed(()=>Math.max(1,...trend.value.flatMap(p=>[p.encrypted,p.plaintext,p.unknown].map(number))))
function lines(key){let current=[];const segments=[];for(const p of trend.value){if(p[key]==null){if(current.length)segments.push(current.join(' '));current=[]}else current.push(`${20+(p.time-((data.value?.timestamp||p.time)-300))/300*760},${150-number(p[key])/maxTrend.value*125}`)}if(current.length)segments.push(current.join(' '));return segments}
const issues=computed(()=>[!monitor.value.enabled?'采集未启用':'',!monitor.value.capture_fresh?'采集没有新数据':'',monitor.value.offload_enabled?'流量卸载可能绕过观察':'',number(monitor.value.dropped_packets)?'出现累计抓包丢失':'',number(monitor.value.evicted_flows)?'部分旧连接已淘汰':'',number(monitor.value.fragmented_packets)?'存在未完整解析分片':'',monitor.value.conntrack_capacity_limited?'连接跟踪达到容量上限':'',monitor.value.core!=='available'?'内核判定暂不可用':''].filter(Boolean))
const updated=computed(()=>data.value?.timestamp?new Date(data.value.timestamp*1000).toLocaleTimeString('zh-CN',{hour12:false}):'等待数据')
async function probe(){if(preview||busy.value)return;busy.value=true;try{const r=await fetch(root+'/probe',{method:'POST',body:new URLSearchParams({token})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'解析验证失败');message.value=d.message;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template>
 <p v-if="error" class="oc-error" role="alert">{{error}}</p><p v-if="message" class="oc-success" role="status">{{message}}</p>
 <section class="oc-privacy-hero"><div class="oc-privacy-shield" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M24 4L40 11V23C40 33 33 40 24 44C15 40 8 33 8 23V11Z"/><path d="M16 23L22 29L33 17"/></svg></div><div><span class="oc-eyebrow">TRAFFIC PRIVACY / 独立保护</span><h2>{{status}}</h2><p>代理关闭后继续保护 DNS。把加密、域名暴露与实际出口分别看清。</p><div class="oc-privacy-pills"><span :class="{ok:dns.firewall_installed}">DNS 防护 {{dns.firewall_installed?'已生效':'待确认'}}</span><span :class="{ok:live}">流量观察 {{live?'实时':'待确认'}}</span><span>更新 {{updated}}</span></div></div><div class="oc-actions"><button :disabled="busy||preview" @click="probe">验证加密解析</button><button class="primary" @click="emit('settings')">保护与监控设置 ↗</button></div></section>
 <div class="oc-privacy-kpis"><article><span>加密迹象比例</span><strong>{{ratio('encrypted')}}</strong><small>{{basis==='count'?'按 WAN 观察记录':'按 WAN 已捕获字节'}} · TLS 握手</small></article><article :class="{risk:dashboard.dns?.wan_plaintext}"><span>WAN 明文 DNS</span><strong>{{metric(dashboard.dns?.wan_plaintext)}}<em>条</em></strong><small>LAN 查询与外部泄露分开计算</small></article><article :class="{risk:dashboard.sni?.overseas}"><span>国外 SNI 暴露</span><strong>{{regionMetric(dashboard.sni?.overseas)}}<em>条</em></strong><small>Clash 归类＋WAN 可见握手</small></article><article :class="{risk:dashboard.risks?.overseas_direct}"><span>国外站点直连</span><strong>{{regionMetric(dashboard.risks?.overseas_direct)}}<em>条</em></strong><small>查看命中规则和节点路径</small></article></div>
 <div class="oc-privacy-dashboard-grid">
  <section class="oc-card oc-privacy-encryption"><header class="oc-privacy-card-head"><div><h3>加密与明文</h3><small>WAN 当前缓存 · 闲置 5 分钟过期</small></div><div class="oc-mini-segments"><button :class="{active:basis==='count'}" @click="basis='count'">连接</button><button :class="{active:basis==='bytes'}" @click="basis='bytes'">字节</button></div></header><div class="oc-donut-layout"><div class="oc-privacy-donut" :style="{background:donut}" role="img" :aria-label="`加密 ${ratio('encrypted')}，明文 ${ratio('plaintext')}，未知 ${ratio('unknown')}`"><div><strong>{{ratio('encrypted')}}</strong><span>加密迹象</span></div></div><div class="oc-donut-legend"><div v-for="p in portions"><i :style="{background:p.color}"></i><span>{{p.label}}</span><b>{{ratio(p.key)}}</b><small>{{live?(basis==='bytes'?bytes(p.value):p.value+' 条'):'等待有效采集'}}</small></div></div></div><p class="oc-privacy-caption">TLS 握手表明加密意图，不证明握手成功、证书验证或远端可信。QUIC、缺失握手及未识别隧道归为未知。</p></section>
  <section class="oc-card"><header class="oc-privacy-card-head"><div><h3>协议分布</h3><small>点击协议查看连接证据</small></div><span class="oc-badge">{{live?dashboard.wan_total?.count||0:'—'}} 条 WAN 记录</span></header><div class="oc-protocol-bars"><button v-for="p in protocolRows" @click="protocol=protocol===p.key?'':p.key;filter='all'" :class="{active:protocol===p.key}"><span>{{p.label}}</span><b>{{basis==='bytes'?bytes(p.value):p.count+' 条'}}</b><i><em :style="{width:p.value/maxProtocol*100+'%',background:p.key==='tls-clienthello'?'#14b8a6':p.key.startsWith('plaintext')?'#f97366':'#93a9c7'}"></em></i></button><p v-if="!protocolRows.length" class="oc-empty">等待 WAN 观察记录，不填充演示数据。</p></div><p class="oc-privacy-caption">字节为缓存内捕获的 WAN 出站字节，不等同总吞吐；连接与 LAN 副本不重复相加；排除本地管理响应 {{dashboard.excluded_management_records||0}} 条。</p></section>
  <section class="oc-card oc-privacy-trend"><header class="oc-privacy-card-head"><div><h3>加密观察趋势</h3><small>后台最近 60 个快照 · 每约 5 秒更新</small></div><span class="oc-badge">{{live?'实时观察':'状态待确认'}}</span></header><div class="oc-privacy-trend-legend"><span v-for="(label,key) in encryptionLabels"><i :style="{background:colors[key]}"></i>{{label}}</span></div><svg viewBox="0 0 800 180" role="img" aria-label="加密、明文和未知连接记录趋势"><path d="M20 25H780 M20 87H780 M20 150H780" stroke="#e9eef6" fill="none"/><g v-for="(label,key) in encryptionLabels"><polyline v-for="(segment,i) in lines(key)" :key="key+i" :points="segment" fill="none" :stroke="colors[key]" stroke-width="2.5"/></g><text x="20" y="174">约 5 分钟前</text><text x="780" y="174" text-anchor="end">现在 · 当前缓存记录数</text></svg><p class="oc-privacy-caption">不是每秒新增事件计数。监控重启清空趋势，缺失采样断线显示。</p></section>
  <section class="oc-card"><header class="oc-privacy-card-head"><div><h3>需要关注</h3><small>点击查看对应记录，不自动修改分流</small></div></header><div class="oc-privacy-risk-list"><button v-for="[key,label,count,note] in risks" @click="focus(key)" :class="{risk:count>0}"><span><strong>{{label}}</strong><small>{{note}}</small></span><b>{{key.startsWith('overseas')?regionMetric(count):metric(count)}}<em> →</em></b></button></div></section>
 </div>
 <div class="oc-privacy-evidence-grid">
  <section class="oc-card"><header class="oc-privacy-card-head"><div><h3>DNS 保护与地域观察</h3><small>DNS 加密不依赖代理运行状态</small></div></header><div class="oc-dns-status-grid"><div><span>加密解析</span><b :class="{ok:dns.health?.available}">{{dns.health?.available===true?'最近验证成功':dns.health?.available===false?'解析失败':'尚未验证'}}</b></div><div><span>失败阻断</span><b :class="{ok:dns.fail_closed}">{{dns.fail_closed?'规则已安装':'未确认'}}</b></div><div><span>LAN 明文查询</span><b>{{metric(dashboard.dns?.lan_plaintext)}} 条</b></div><div><span>WAN 明文查询</span><b :class="{risk:dashboard.dns?.wan_plaintext}">{{metric(dashboard.dns?.wan_plaintext)}} 条</b></div></div><div class="oc-region-evidence"><div v-for="g in geoRows"><strong>{{g.label}}<small>{{g.count||g.lan_dns||g.plaintext_dns?'WAN 明文 '+(g.plaintext_dns?'已发现':'暂无证据'):'尚无可归类证据'}}</small></strong><span>WAN 明文 DNS <b :class="{risk:g.plaintext_dns}">{{metric(g.plaintext_dns)}}</b></span><span>可见 SNI <b>{{metric(g.sni)}}</b></span><span>直连 <b>{{metric(g.direct)}}</b></span></div></div><p class="oc-privacy-caption">加密 DNS 内的查询域名不可被被动读取，因此不能逐条证明国内外查询都安全。明文查询可通过近期同域名的 Clash 判定关联；无关联时归类未知。</p></section>
  <section class="oc-card"><header class="oc-privacy-card-head"><div><h3>SNI 与出口路径</h3><small>正文加密和域名隐藏是两件事</small></div></header><div class="oc-sni-primary"><div><strong>{{metric(dashboard.sni?.visible)}}</strong><span>WAN 可读 SNI</span></div><div><strong>{{regionMetric(dashboard.sni?.overseas)}}</strong><span>其中国外站点</span></div><div><strong>{{metric(dashboard.sni?.unknown)}}</strong><span>地域未判定</span></div></div><div class="oc-path-summary"><div v-for="[key,label] in [['proxy','节点路径'],['direct','直连路径'],['unknown','路径未知'],['conflicting','证据冲突']]"><span>{{label}}</span><b>{{metric(dashboard.routes?.[key])}}</b></div></div><p class="oc-privacy-caption">WAN 提出 ECH {{metric(dashboard.sni?.ech_offered)}} 条，提出 TLS 1.3 {{metric(dashboard.sni?.tls13_offered)}} 条；提出不等于生效。没有读到 SNI 也不等于隐藏成功，目标 IP 仍可能可见。</p></section>
 </div>
 <section class="oc-card oc-privacy-coverage"><header class="oc-privacy-card-head"><div><h3>观察覆盖与可信边界</h3><small>不提供误导性的综合“安全分”</small></div><span class="oc-badge">{{issues.length?'存在覆盖限制':'当前采集状态正常'}}</span></header><div class="oc-coverage-summary"><span>WAN {{data?.config?.wan_interface||'未读取'}}</span><span>LAN {{list(data?.config?.lan_interface).join('、')||'未读取'}}</span><span>内核 {{monitor.core||'未知'}}</span><span>Clash 已归类 {{classified}} 条 · 未归类 {{dashboard.geography?.unknown?.count||0}} 条</span><span>抓包丢失 {{monitor.dropped_packets||0}}</span><span>缓存淘汰 {{monitor.evicted_flows||0}}</span></div><p v-if="issues.length" class="oc-coverage-issues">{{issues.join(' · ')}}</p><p class="oc-privacy-caption">国内外只复用 Mihomo 命中规则或 destinationGeoIP，不以 DIRECT／PROXY 推断地域，也不使用独立网站库。未经过内核、未查询 GeoIP 或内核关闭时，地域可能未知。当前只覆盖配置的接口；分片、卸载、容量和缺失握手会影响结果。元数据及趋势仅在 RAM。</p></section>
 <section id="privacy-connections" class="oc-privacy-connections"><header class="oc-privacy-card-head"><div><h3>连接证据</h3><small>点击连接查看规则、观察位置与暴露依据</small></div><button @click="load()">刷新</button></header><div class="oc-toolbar"><input v-model="search" type="search" aria-label="搜索监控连接" placeholder="设备 IP、目标 IP 或域名"><select v-model="filter" aria-label="流量筛选"><option value="all">全部记录</option><option value="overseas-sni">国外 SNI 暴露</option><option value="overseas-direct">国外站点直连</option><option value="dns">WAN 明文 DNS</option><option value="plaintext">WAN 明文流量</option><option value="sni">所有 WAN 可见 SNI</option><option value="proxy">经过节点</option><option value="direct">直连</option><option value="unknown">路径未知</option><option value="watched">关注域名直连</option></select><select v-model="region" aria-label="地域筛选"><option value="all">全部地域</option><option v-for="(label,key) in regions" :value="key">{{label}}</option></select><button v-if="protocol" @click="protocol=''">{{protocols[protocol]||protocol}} ×</button></div><div class="oc-flow-table"><table><thead><tr><th>来源设备</th><th>目标与 Clash 判定</th><th>实际路径</th><th>隐私证据</th><th>字节</th></tr></thead><tbody><tr v-for="f in data?.flows||[]" :key="f.id" :class="{alert:f.wan_plain_dns||f.overseas_sni||f.overseas_direct}" tabindex="0" @click="selected=f" @keydown.enter="selected=f"><td>{{f.source}}<small>{{f.source_port}} · IPv{{f.ip_version}}</small></td><td>{{f.domain||f.core_destination||f.destination}}<small>{{regions[f.site_region]||regions.unknown}} · {{f.core_destination||f.destination}}:{{f.core_port||f.destination_port}}</small></td><td>{{routes[f.route]||f.route}}<small>{{list(f.chains).join(' → ')||f.rule||'尚未关联内核'}}</small></td><td>{{protocols[f.protocol_evidence]||f.protocol_evidence}}<small :class="{risk:f.wan_sni_visible||f.wan_plain_dns}">{{f.wan_plain_dns?'WAN 上可读 DNS 查询':f.wan_sni_visible?'WAN 上可读 SNI':'域名隐藏状态未确认'}}</small></td><td>{{bytes(f.bytes)}}</td></tr><tr v-if="!data?.flows?.length"><td colspan="5">暂无匹配记录；零记录不代表零风险。</td></tr></tbody></table></div><div class="oc-flow-pagination"><span>{{data?.total||0}} 条 · 每页 {{data?.limit||50}} 条</span><button :disabled="page<=1" @click="page--;load()">上一页</button><button :disabled="page*(data?.limit||50)>=(data?.total||0)" @click="page++;load()">下一页</button></div></section>
 <div v-if="selected" class="oc-privacy-detail-overlay" @click.self="selected=null"><section class="oc-privacy-detail" tabindex="-1" role="dialog" aria-modal="true" aria-label="连接隐私证据" @keydown.esc="selected=null"><header><div><span class="oc-eyebrow">CONNECTION EVIDENCE</span><h3>{{selected.domain||selected.destination}}</h3></div><button @click="selected=null">关闭详情</button></header><dl><dt>Clash 国内外判定</dt><dd>{{regions[selected.site_region]||regions.unknown}}<small>{{selected.site_region_evidence||'缺少内核证据'}}</small></dd><dt>命中规则</dt><dd>{{selected.rule||'未获取'}} · {{selected.rule_payload||'无规则内容'}}<small>{{list(selected.chains).join(' → ')||'未关联节点路径'}}</small></dd><dt>实际出口路径</dt><dd>{{routes[selected.route]}}<small>{{selected.route_evidence}}</small></dd><dt>WAN 暴露证据</dt><dd>{{selected.wan_plain_dns?'观察到明文 DNS 查询':selected.wan_sni_visible?'观察到可读 TLS SNI':'没有直接域名暴露证据，隐藏状态仍未知'}}<small>{{selected.wan_protocol?protocols[selected.wan_protocol]:'未关联 WAN 握手'}} · {{selected.vantage}}</small></dd><dt>传输加密与 ECH</dt><dd>{{protocols[selected.protocol_evidence]}}<small>{{selected.wan_ech_offered?'WAN 上提出 ECH，接受状态未知':'没有 WAN ECH 生效证据'}}；不能据此证明证书校验、远端可信或应用没有其他泄露。</small></dd><dt>连接端点</dt><dd>{{selected.source}}:{{selected.source_port}} → {{selected.destination}}:{{selected.destination_port}}<small>{{selected.core_destination?'内核目标 '+selected.core_destination+':'+selected.core_port:''}}</small></dd></dl><button class="primary" @click="selected=null">返回仪表盘</button></section></div>
</template>
