<script setup>
import { onMounted, reactive, ref } from 'vue'
import { base, preview, request, token } from '../api.js'
const emit=defineEmits(['dirty']),records=ref({}),selected=ref(''),busy=ref(false),error=ref(''),message=ref(''),content=ref('')
const form=reactive({filename:'',old_filename:'',type:'file',url:'',config:'',enable:'1',order:'0',update_days:'',update_hour:'',param:''})
async function load(){try{records.value=(await request('overwrite_subscribe_info')).data||{}}catch(e){error.value=e.message}}
onMounted(load)
function choose(name){selected.value=name;const row=records.value[name]||{};Object.assign(form,{filename:name,old_filename:name,type:'file',url:'',config:'',enable:'1',order:'0',update_days:'',update_hour:'',param:''},row,{enable:String(row.enable??1),order:String(row.order??0),config:Array.isArray(row.config)?row.config.join('\n'):row.config||''});content.value='';emit('dirty',false)}
async function run(operation){if(preview||busy.value)return
 if(operation!=='delete'&&!/^[\w.-]{1,128}$/.test(form.filename)){error.value='文件名填写 1–128 位字母、数字、下划线、点或连字符';return}
 if(operation!=='delete'&&(!/^\d+$/.test(String(form.order))||Number(form.order)>65535)){error.value='顺序需为 0–65535 的整数';return}
 if(operation!=='delete'&&form.update_days&&!/^(\*|[0-6](,[0-6])*)$/.test(form.update_days)){error.value='更新星期需为 0–6 的逗号列表、* 或留空';return}
 if(operation!=='delete'&&form.update_hour&&!/^(\*|[0-9]|1[0-9]|2[0-3])$/.test(form.update_hour)){error.value='更新时间需为 0–23、* 或留空';return}
 if(operation!=='delete'&&(form.param.length>4096||form.param.includes('\u0000'))){error.value='脚本参数最多 4096 字符，不能含空字符';return}
 if(operation==='save'&&form.type==='http'){try{const u=new URL(form.url);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error()}catch{error.value='订阅地址需为单个 HTTP / HTTPS URL';return}}
 if(operation==='delete'&&!confirm('删除这个覆写文件及其订阅记录？'))return
 busy.value=true;try{const r=await fetch(`${base}/modern_overwrite`,{method:'POST',body:new URLSearchParams({...form,config_file:content.value,operation,token})});const d=await r.json();if(!r.ok||d.status==='error'||d.error)throw Error(d.error||d.message||`操作失败 ${r.status}`);message.value='覆写记录已保存';emit('dirty',false);await load();if(operation==='delete')choose('')}catch(e){error.value=e.message}finally{busy.value=false}}
async function read(){try{content.value=(await request('config_file_read',{config_file:'/etc/openclash/overwrite/'+form.filename})).content||''}catch(e){error.value=e.message}}
</script>
<template><p v-if="error" class="oc-error" role="alert">{{error}}</p><p v-if="message" class="oc-success">{{message}}</p><div class="oc-files"><aside><h3>覆写文件与订阅</h3><button @click="choose('')">＋ 新建覆写记录</button><button v-for="(record,name) in records" :class="{active:selected===name}" @click="choose(name)">{{name}}<small>{{record.type==='http'?'订阅':'本地文件'}} · 顺序 {{record.order}}</small></button></aside><section class="oc-security-config" @input="emit('dirty',true)" @change="emit('dirty',true)"><label>文件名<input v-model="form.filename"><small>1–128 位字母、数字、下划线、点或连字符，建议带 .yaml / .sh 后缀。</small></label><label>来源<select v-model="form.type"><option value="file">本地文件</option><option value="http">HTTP / HTTPS 订阅</option></select></label><label v-if="form.type==='http'">订阅地址<input v-model="form.url"><small>单个完整 HTTP / HTTPS URL；推荐 HTTPS。</small></label><label>适用配置<textarea v-model="form.config" rows="2"></textarea><small>每行一个配置文件名；留空应用于全部配置。</small></label><label class="oc-security-toggle"><input type="checkbox" :checked="form.enable==='1'" @change="form.enable=$event.target.checked?'1':'0'"><span>启用此覆写<small>建议只启用需要的覆写内容。</small></span></label><label>执行顺序<input v-model="form.order" inputmode="numeric"><small>0–65535，推荐按执行顺序递增。</small></label><label>更新星期<input v-model="form.update_days"><small>留空不定时更新；0–6 分别为星期日到星期六，可用逗号分隔，* 为每天。</small></label><label>更新时间<input v-model="form.update_hour"><small>0–23 的小时或 *，留空不指定。</small></label><label>脚本参数<input v-model="form.param"><small>传给自定义覆写脚本的参数，最多 4096 字符；普通 YAML 留空。</small></label><div class="oc-actions"><button :disabled="busy||preview" @click="run('save')">保存覆写信息</button><button :disabled="busy||preview||!selected" @click="run('delete')">删除记录与文件</button><button :disabled="busy||!form.filename" @click="read">读取文件</button></div><label>上传 / 编辑覆写内容<input type="file" @change="async e=>{if(e.target.files[0]?.size>10485760){error='文件最多 10 MiB';return}content=await e.target.files[0].text();emit('dirty',true)}"><textarea v-model="content" rows="9" aria-label="覆写文件内容"></textarea><small>最多 10 MiB；.yaml / .yml 会检查语法，脚本按原格式保存。</small></label><button class="primary" :disabled="busy||preview||!content" @click="run('upload')">保存文件及覆写设置</button></section></div></template>
