<script setup>
import {ref,watch} from 'vue'
import {base,token,request,preview} from '../api.js'
const props=defineProps(['status'])
const busy=ref(false),output=ref(''),outputTitle=ref(''),rule=ref('rule'),run=ref(''),domain=ref('example.com')
const location=window.location
const sites=[['百度','www.baidu.com'],['网易云音乐','music.163.com'],['GitHub','github.com'],['YouTube','www.youtube.com']]
const results=ref({}),siteBusy=ref(false)
watch(()=>props.status,s=>{if(s){rule.value=s.rule_mode||'rule';run.value=s.run_mode?.includes('混合')||s.run_mode?.includes('mix')?'-mix':s.run_mode?.includes('TUN')||s.run_mode?.includes('tun')?'-tun':''}},{immediate:true})
async function post(operation,extra={}){const r=await fetch(`${base}/modern_tools`,{method:'POST',body:new URLSearchParams({operation,...extra,token})});const text=await r.text();if(!r.ok)throw Error(`操作失败 ${r.status}`);try{return JSON.parse(text)}catch{return text||'操作已提交'}}
function readable(data){if(typeof data==='string')return data;const names={cpu:'CPU 占用',load_avg:'系统负载',mixed_port:'混合代理端口',auth_user:'认证用户名',cn_port:'控制端口',clash:'代理服务',daip:'控制地址',website_check:'访问结果',website_status:'访问状态',website_delay:'请求耗时',pac:'PAC 地址'};return Object.entries(data||{}).filter(([k])=>!['auth_pass','dase'].includes(k)).map(([k,v])=>`${names[k]||k}：${typeof v==='object'?JSON.stringify(v):v}`).join('\n')||'操作已提交'}
async function execute(operation,extra={},title='操作结果'){if(preview||busy.value)return;if(operation==='website_check'&&(!/^[a-z\d](?:[a-z\d.-]*[a-z\d])?$/i.test(domain.value)||domain.value.includes('..')||domain.value.length>253)){output.value='填写域名，例如 example.com，不能包含协议或路径';return}busy.value=true;outputTitle.value=title;try{output.value=readable(await post(operation,extra))}catch(e){output.value=e.message}finally{busy.value=false}}
async function read(action,title){if(busy.value||preview)return;busy.value=true;outputTitle.value=title;try{output.value=readable(await request(action))}catch(e){output.value=e.message}finally{busy.value=false}}
async function checkSites(){if(siteBusy.value||preview)return;siteBusy.value=true;await Promise.allSettled(sites.map(async([name,host])=>{results.value[host]={state:'检测中'};try{const value=await post('website_check',{domain:host});results.value[host]={state:'检测完成',text:readable(value)}}catch(e){results.value[host]={state:'检测失败',text:e.message}}}));siteBusy.value=false}
</script>
<template><section class="oc-control-section"><header class="oc-section-heading"><h3>运行控制与网络工具</h3><span>常用操作直接显示</span></header><div class="oc-control-grid"><article class="oc-card"><h3>代理模式</h3><p>规则分流、全局代理与全部直连。</p><div class="oc-segmented"><button v-for="(label,value) in {rule:'规则分流',global:'全局代理',direct:'全部直连'}" :class="{active:rule===value}" :disabled="busy||preview" @click="rule=value;execute('switch_rule_mode',{rule_mode:value},'代理模式')">{{label}}</button></div></article><article class="oc-card"><h3>流量接管</h3><p>切换接管方式会重新载入代理服务。</p><div class="oc-segmented"><button v-for="[value,label] in [['','普通接管'],['-tun','TUN'],['-mix','混合接管']]" :class="{active:run===value}" :disabled="busy||preview" @click="run=value;execute('switch_run_mode',{run_mode:value},'流量接管')">{{label}}</button></div></article><article class="oc-card oc-quick-tools"><h3>维护与连接</h3><div class="oc-tool-buttons"><button :disabled="busy||preview" @click="execute('close_all_connection',{},'关闭代理连接')">关闭代理连接</button><button :disabled="busy||preview" @click="execute('reload_firewall',{},'重载代理防火墙')">重载防火墙</button><button :disabled="busy||preview" @click="execute('flush_dns_cache',{},'清理 DNS 缓存')">清理 DNS 缓存</button><button :disabled="busy||preview" @click="read('conn_status','控制接口')">控制接口</button><button :disabled="busy||preview" @click="read('toolbar_show_sys','内核资源')">内核资源</button><button :disabled="busy||preview" @click="read('proxy_info','本地代理入口')">代理入口</button><button :disabled="busy||preview" @click="read('announcement','上游公告')">上游公告</button><button :disabled="busy||preview" @click="execute('generate_pac',{client_protocol:location.protocol.replace(':',''),client_hostname:location.hostname,client_host:location.host,client_port:location.port,client_href:location.href},'PAC 地址')">生成 PAC</button></div></article></div><article v-if="output" class="oc-card oc-operation-result" role="status"><header><strong>{{outputTitle}}</strong><button @click="output=''">关闭结果</button></header><pre>{{output}}</pre></article><div class="oc-network-grid"><section class="oc-card oc-site-section"><header class="oc-card-heading"><div><h3>访问检查</h3><p>由路由器发起 HTTPS 请求，逐个显示本次结果。</p></div><button :disabled="siteBusy||preview" @click="checkSites">{{siteBusy?'检测中…':'检测四个网站'}}</button></header><div class="oc-site-grid"><article v-for="[name,host] in sites"><strong>{{name}}</strong><small>{{results[host]?.state||'未检测'}}</small><p>{{results[host]?.text||host}}</p></article></div><form class="oc-domain-check" @submit.prevent="execute('website_check',{domain},'自定义网站检查')"><label>自定义域名<input v-model="domain" aria-label="测试网站域名" placeholder="example.com"></label><button :disabled="busy||preview">检测网站</button><small>只填域名，不包含 https:// 或路径。</small></form></section><slot/></div></section></template>
