import {chromium,expect} from '@playwright/test'
import {writeFile} from 'node:fs/promises'
const root='http://127.0.0.1:18081',privacy=root+'/cgi-bin/luci/admin/services/router_privacy',node=root+'/cgi-bin/luci/admin/services/router_node_health'
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],report={}
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept())
const nav=name=>page.locator('nav').getByRole('button',{name:new RegExp(name)})
try{
 await page.goto(root+'/#security');await page.locator('.oc-privacy-donut').waitFor();await page.getByRole('heading',{name:'独立保护运行中',exact:true}).waitFor()
 const actual=await(await page.request.get(privacy+'/status')).json();if(actual.error||!actual.dashboard?.available)throw Error('Missing real dashboard snapshot')
 const d=actual.dashboard;for(const key of ['count','bytes'])if(['encrypted','plaintext','unknown'].reduce((n,k)=>n+d.encryption[k][key],0)!==d.wan_total[key])throw Error('WAN totals double counted')
 if(d.trend.length>60)throw Error('Unbounded trends')
 report.actual_analytics=true;report.no_settings_below_dashboard=await page.locator('.oc-monitor-settings').count()===0
 await page.screenshot({path:'../artifacts/privacy-dashboard-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});report.dashboard_mobile_overflow=await page.locator('#openclash-modern').evaluate(e=>e.scrollWidth>e.clientWidth+1);await page.screenshot({path:'../artifacts/privacy-dashboard-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1100})
 for(const[query,predicate]of [['protocol=tls-clienthello',f=>f.wan_protocol==='tls-clienthello'||f.protocol_evidence==='tls-clienthello'],['region=overseas',f=>f.site_region==='overseas'],['filter=dns',f=>f.wan_plain_dns]]){const data=await(await page.request.get(privacy+'/status?'+query)).json();if((Array.isArray(data.flows)?data.flows:[]).some(f=>!predicate(f)))throw Error('Incorrect evidence filter')}
 report.backend_filters=true
 await page.getByRole('button',{name:'保护与监控设置 ↗',exact:true}).click();await page.getByRole('heading',{name:'隐私监控设置',exact:true}).waitFor();await page.getByLabel('独立 DNS 本地端口',{exact:true}).waitFor();if(await page.locator('.oc-privacy-donut').count())throw Error('Settings mixed into dashboard')
 let polls=0;const listener=r=>{if(r.url().includes('/router_privacy/status'))polls++};page.on('request',listener);await page.waitForTimeout(5500);page.off('request',listener);if(polls)throw Error('Dashboard polls continued on settings page')
 const configBefore=await(await page.request.get(privacy+'/settings')).json();const port=await page.getByLabel('独立 DNS 本地端口',{exact:true}).inputValue();await page.getByLabel('独立 DNS 本地端口',{exact:true}).fill('53531');await page.getByRole('button',{name:'保存设置',exact:true}).click();await expect(page.locator('.oc-error')).toContainText('1024');const after=await(await page.request.get(privacy+'/settings')).json();if(JSON.stringify(after)!==JSON.stringify(configBefore))throw Error('Invalid settings changed config')
 await page.getByLabel('独立 DNS 本地端口',{exact:true}).fill(port);await page.getByRole('button',{name:'保存设置',exact:true}).click();await page.locator('.oc-success').waitFor();await page.setViewportSize({width:390,height:844});report.settings_mobile_overflow=await page.locator('#openclash-modern').evaluate(e=>e.scrollWidth>e.clientWidth+1);await page.screenshot({path:'../artifacts/privacy-settings-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1100});report.privacy_settings_roundtrip=true
 await page.getByRole('button',{name:'← 返回隐私仪表盘',exact:true}).click();await page.locator('.oc-privacy-donut').waitFor();await nav('节点监控').click();await page.getByRole('button',{name:'监控设置',exact:true}).click();await page.getByRole('heading',{name:'节点监控设置',exact:true}).waitFor();await page.getByLabel('每节点检测间隔（秒）',{exact:true}).waitFor();if(await page.locator('.oc-health-layout').count())throw Error('Node settings mixed into dashboard')
 const nodeBefore=await(await page.request.get(node+'/settings')).json();const interval=await page.getByLabel('每节点检测间隔（秒）',{exact:true}).inputValue();await page.getByLabel('每节点检测间隔（秒）',{exact:true}).fill('29');await page.getByRole('button',{name:'保存设置',exact:true}).click();await expect(page.locator('.oc-error')).toContainText('30–3600');if(JSON.stringify(await(await page.request.get(node+'/settings')).json())!==JSON.stringify(nodeBefore))throw Error('Invalid node setting changed config')
 await page.getByLabel('每节点检测间隔（秒）',{exact:true}).fill(interval);await page.getByRole('button',{name:'保存设置',exact:true}).click();await page.locator('.oc-success').waitFor();report.node_settings_roundtrip=true
 await page.reload();await page.getByRole('heading',{name:'节点监控设置',exact:true}).waitFor();report.settings_route_survives_reload=true
 // Component fixtures are isolated from real services and removed afterward.
 const now=Math.floor(Date.now()/1000),fixture=structuredClone(actual);fixture.timestamp=now;fixture.dashboard.geography.overseas.count=2;fixture.dashboard.geography.overseas.sni=1;fixture.dashboard.sni.overseas=1;fixture.dashboard.risks.overseas_direct=1;fixture.dashboard.encryption={encrypted:{count:2,bytes:200},plaintext:{count:1,bytes:100},unknown:{count:1,bytes:100}};fixture.dashboard.wan_total={count:4,bytes:400};fixture.dashboard.available=true;fixture.dashboard.trend=[{time:now-10,encrypted:1,plaintext:1,unknown:1},{time:now-5,encrypted:null,plaintext:null,unknown:null},{time:now,encrypted:2,plaintext:1,unknown:1}];fixture.flows=[{id:'component-fixture',source:'192.0.2.2',source_port:40000,destination:'198.51.100.1',destination_port:443,domain:'privacy-fixture.example',site_region:'overseas',site_region_evidence:'mihomo-rule:geosite:geolocation-!cn',route:'direct-observed',route_evidence:'conntrack-reply-tuple+wan-packet',protocol_evidence:'tls-clienthello',wan_protocol:'tls-clienthello',wan_sni_visible:true,overseas_sni:true,overseas_direct:true,rule:'GeoSite',rule_payload:'geolocation-!cn',network:'tcp',ip_version:4,bytes:200,chains:[]}];fixture.total=1
 await page.route('**/router_privacy/status?*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(fixture)}));await nav('隐私监控').click();await expect(page.locator('.oc-privacy-kpis').first()).toContainText('50.0%');await expect(page.locator('.oc-privacy-kpis article').nth(2)).toContainText('1');await page.getByRole('button',{name:'字节',exact:true}).click();await expect(page.locator('.oc-privacy-donut')).toContainText('50.0%');if(await page.locator('.oc-privacy-trend polyline').count()!==6)throw Error('Missing samples did not split chart')
 await page.locator('.oc-flow-table tbody tr').first().click();await page.getByRole('dialog',{name:'连接隐私证据'}).waitFor();await expect(page.getByRole('dialog')).toContainText('geolocation-!cn');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 fixture.stale=true;fixture.monitor.enabled=false;await page.getByRole('button',{name:'刷新',exact:true}).click();await expect(page.locator('.oc-privacy-kpis article').first()).toContainText('—');report.unknown_stale_not_safe=true;report.fixture_ratio_and_evidence=true;report.missing_samples_break_chart=true;await page.unroute('**/router_privacy/status?*')
 report.page_errors=errors;if(errors.length||report.dashboard_mobile_overflow||report.settings_mobile_overflow)throw Error(JSON.stringify(report));await writeFile('../artifacts/privacy-dashboard-test.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
}catch(e){await page.screenshot({path:'../artifacts/privacy-dashboard-failure.png',fullPage:true});console.error(e,errors);process.exitCode=1}finally{await browser.close()}
