// Supplement fields whose upstream CBI definition has no description.
// Legal choices and defaults are always read from the live CBI model.
export const parameterPurpose = {
 ipv6_mode:'选择 IPv6 连接的接管方式；与 IPv4 模式分别配置，TUN 与混合模式还需要选择网络栈。',
 custom_name_policy:'启用按域名指定 DNS 的覆写策略；具体匹配与服务器映射在下方对应的 YAML 参数中填写。',
 custom_proxy_server_policy:'启用节点服务器域名的 DNS 覆写策略，为代理建立连接提供独立解析路径。',
 global_ua:'设置内核发起下载请求时使用的 User-Agent，影响部分订阅或资源服务器返回的内容。',
 lgbm_update_interval:'设置 LightGBM 模型自动更新间隔，单位小时；仅在自动更新开启时生效。',
 enabled:'控制当前记录是否参与配置生成或定时处理；关闭会保留记录供以后重新启用。',
 type:'选择当前记录的协议或工作类型；切换后只显示适用于该类型的参数。',
 disable_ipv6:'禁止当前 DNS 上游返回 IPv6 解析结果；这不等于禁止客户端的 IPv6 网络连接。',
 config_auto_update_mode:'选择订阅自动更新采用固定时刻还是间隔运行；与同组的时间参数一起设置。',
 config_update_interval:'设置订阅自动更新的时间间隔，单位小时；间隔模式启用后生效。',
 template:'选择订阅转换模板；模板决定生成的策略组和规则，必须与所用转换服务兼容。',
 mtime:'显示文件最近修改时间，供判断订阅、配置或资源是否更新。',
 size:'显示文件大小，供判断资源占用；这是读取结果，无需输入。',
 actions:'对当前文件执行原有文件管理操作，例如下载、编辑或删除；先核对目标文件。',
 num:'显示当前文件的序号或统计数量，作为列表定位信息，无需输入。',
 user:'编辑磁盘中的原始配置内容；保存后由 OpenClash 在应用配置时生成运行配置。',
 default:'查看生成后的运行配置内容，用于核对实际生效结果与原始配置的差异。',
 flag_port_hopping:'启用 Hysteria 端口跳跃；服务端必须在设置的端口范围中提供对应监听。',
 ports:'设置端口跳跃的起止端口范围，范围必须与服务端和防火墙开放范围一致。',
 aead_method:'选择 Sudoku 节点使用的 AEAD 加密方式，必须与服务端的协议参数一致。',
 padding_min:'设置 Sudoku 填充参数的下限；与填充上限共同控制填充开销，需符合服务端要求。',
 padding_max:'设置 Sudoku 填充参数的上限；过大的填充会增加传输开销，需与下限配套。',
 table_type:'选择 Sudoku 编码表的类型，必须与服务端约定的编码方式一致。',
 http_mask:'设置 Sudoku 的 HTTP 伪装行为，决定流量封装是否采用对应的 HTTP 形式。',
 port_range:'设置该协议使用的服务器端口范围；按服务端提供的范围填写，不能替代单端口字段。',
 username:'填写当前协议的登录用户名，必须与服务端认证记录一致。',
 transport:'选择当前协议的传输方式，必须匹配服务端的监听和支持能力。',
 tc_ip:'显式指定 TUIC 服务器 IP，覆盖服务器域名解析得到的连接地址。',
 udp_relay_mode:'选择 TUIC UDP 转发采用原生数据报还是 QUIC 流；需要结合服务端和业务选择。',
 congestion_controller:'选择 QUIC 拥塞控制算法，影响丢包、带宽利用率和延迟表现。',
 reduce_rtt:'启用 TUIC 提前发送握手数据以减少等待；0-RTT 数据具有重放方面的取舍。',
 heartbeat_interval:'设置 TUIC 心跳间隔，单位毫秒；用于保持和检查连接，过短会增加请求开销。',
 request_timeout:'设置 TUIC 请求超时，单位毫秒；超时过短可能把较慢的连接判为失败。',
 max_udp_relay_packet_size:'设置 TUIC 允许转发的 UDP 包大小上限，单位字节。',
 max_open_streams:'限制 TUIC 最大并发流数量；较高上限可处理更多并发，也会增加资源占用。',
 wg_ip:'填写 WireGuard 客户端在隧道中的 IPv4 地址，使用服务端为该客户端分配的地址。',
 wg_ipv6:'填写 WireGuard 客户端在隧道中的 IPv6 地址，使用服务端为该客户端分配的地址。',
 wg_dns:'指定 WireGuard 节点使用的 DNS 服务器地址列表，按当前节点的解析路径填写。',
 flag_transport:'显示并启用该 Hysteria 节点的传输参数；这些参数需与所用协议版本和服务端一致。',
 hysteria_protocol:'选择 Hysteria v1 的传输协议形式，必须与服务端支持的形式一致。',
 hysteria2_protocol:'选择 Hysteria v2 的传输形式，不能混用 Hysteria v1 的传输参数。',
 snell_version:'选择 Snell 协议版本，必须与服务器实际运行的版本兼容。',
 cipher:'选择 Shadowsocks 的加密算法，算法与密钥需匹配服务器配置。',
 cipher_ssr:'选择 ShadowsocksR 的加密算法，需同时匹配其协议和混淆设置。',
 protocol:'选择 ShadowsocksR 的认证协议，必须与服务端配置一致。',
 protocol_param:'填写 ShadowsocksR 认证协议的附加参数；是否需要填写由所选协议和服务端决定。',
 securitys:'选择 VMess 的加密方式，必须受所用内核和服务端支持。',
 obfs_ssr:'选择 ShadowsocksR 的混淆方式，配合混淆参数使用。',
 obfs_param:'填写 ShadowsocksR 混淆方式的附加参数，不能使用其他协议的路径或密码代替。',
 alterId:'填写旧版 VMess 的额外身份数量；现代配置通常由订阅提供 0，必须与服务端一致。',
 udp:'控制该节点或订阅生成结果是否启用 UDP；服务端也必须提供 UDP 支持。',
 udp_over_tcp:'启用当前协议的 UDP over TCP 封装；必须由服务端支持，可能增加丢包时的等待。',
 xudp:'启用支持协议的 XUDP 封装，改善 UDP 复用行为；需确认服务端支持。',
 obfs:'选择当前节点的混淆或传输封装方式；切换后显示配套的 Host、路径或密钥参数。',
 obfs_snell:'选择 Snell 的混淆方式，需匹配服务端部署。',
 obfs_vless:'选择 VLESS 的传输封装，需匹配服务端的 WebSocket、gRPC 等监听方式。',
 obfs_vmess:'选择 VMess 的传输封装，需匹配服务端监听和反向代理配置。',
 obfs_trojan:'选择 Trojan 的传输封装，需匹配服务端的普通 TLS 或 WebSocket 等部署。',
 obfs_version_hint:'设置 Restls 的版本提示，需与服务端使用的握手方案匹配。',
 obfs_restls_script:'填写 Restls 的握手脚本参数；应直接使用服务端提供的脚本，不自行拼接。',
 custom:'填写 HTTP 传输的附加请求头，字段名和值必须与服务端要求一致。',
 vless_encryption:'设置 VLESS 的加密参数，需与服务端提供的配置一致。',
 vless_flow:'选择 VLESS 流控方式；只有服务端支持的 Flow 才能使用。',
 grpc_service_name:'填写 gRPC 的服务名称，需匹配服务器监听及反向代理路径。',
 max_early_data:'限制 WebSocket 提前发送的数据量；必须匹配服务端支持能力。',
 early_data_header_name:'指定 WebSocket 提前发送数据使用的请求头名称，需与服务端约定一致。',
 keep_alive:'控制该传输是否保持底层连接，影响连接复用和空闲连接资源占用。',
 auth_name:'填写当前协议的认证用户名，需与服务端账号对应。',
 auth_pass:'填写当前协议的认证密码，需与认证用户名和服务端记录对应。',
 hysteria_obfs:'选择 Hysteria 的混淆方式；与对应混淆密码和服务端参数一起配置。',
 hysteria_auth_str:'填写 Hysteria v1 的认证字符串，使用服务端提供的原始内容。',
 hysteria_ca:'指定 Hysteria 自定义 CA 证书文件路径，文件必须存在于路由器并可读取。',
 hysteria_ca_str:'直接填写 Hysteria 自定义 CA 证书内容，应为可信的 PEM 证书文本。',
 flag_quicparam:'启用自定义 QUIC 窗口等高级参数，影响缓存规模和连接行为。',
 hop_interval:'设置 Hysteria 端口跳跃的间隔，单位秒；仅在启用端口跳跃时生效。',
 'packet-addr':'启用当前协议的封包地址扩展，用于 UDP 目标地址传递；服务端必须支持该扩展。',
 packet_encoding:'选择 UDP 数据包地址编码形式，必须与服务端实现兼容。',
 global_padding:'控制支持协议的全局填充行为；填充会改变数据长度并增加传输开销。',
 authenticated_length:'控制支持协议的长度认证扩展，必须与服务器协议实现一致。',
 idle_session_check_interval:'设置 AnyTLS 检查空闲会话的间隔，单位秒，影响空闲连接清理频率。',
 idle_session_timeout:'设置 AnyTLS 空闲会话超时，单位秒；到期后的空闲会话可被清理。',
 min_idle_session:'设置 AnyTLS 保留的最少空闲会话数量，以连接预留资源换取更快的后续建连。',
 masque_ip:'填写 MASQUE 客户端的隧道 IPv4 地址，需与服务端分配的地址对应。',
 masque_ipv6:'填写 MASQUE 客户端的隧道 IPv6 地址，需与服务端分配的地址对应。',
 masque_remote_dns_resolve:'控制 MASQUE 是否在远端解析目标域名，影响解析请求的实际出口。',
 masque_dns:'填写 MASQUE 使用的 DNS 服务器地址列表，与远端解析设置配套。',
 trusttunnel_username:'填写 TrustTunnel 的认证用户名，需与服务器账号匹配。',
 trusttunnel_health_check:'控制 TrustTunnel 连接健康检查，便于发现失效连接，也增加检查开销。',
 trusttunnel_quic:'控制 TrustTunnel 是否使用 QUIC 传输，需要服务端支持该传输方式。',
 trusttunnel_congestion_controller:'选择 TrustTunnel QUIC 拥塞控制方式，需结合实际网络条件测试。',
 fast_open:'启用 TUIC 的快速连接行为以减少建立连接的等待，需结合服务端兼容性测试。',
 tfo:'控制 TCP Fast Open，尝试在握手阶段发送数据，需要系统和服务端支持。',
 ip_version:'选择出站连接优先使用的 IP 地址版本；选定地址族必须有可用网络出口。',
 disable_udp:'禁止当前策略组使用 UDP；会影响依赖该组的 UDP 业务，不能补齐节点能力。',
 icon:'填写策略组图标地址，供兼容的 Dashboard 展示；不影响代理规则匹配。',
 custom_template_url:'填写订阅转换的自定义模板地址，服务必须能够获取该模板。',
 emoji:'控制订阅转换生成的节点名称是否带地区 Emoji，便于面板辨识。',
 sort:'控制订阅转换结果是否进行节点排序，可能改变列表中节点的原始顺序。',
 node_type:'控制订阅转换生成的名称是否显示节点协议类型，便于区别同名节点。',
 edit_file:'编辑所选文件的原始文本；按文件类型保持 YAML、Shell 或其他配置语法。'
}
