local h=dofile(arg[1]);local n=h.new('fixture','Socks5',1000)
h.record(n,1000,100,nil,3,'https://example.com/')
h.record(n,1060,nil,'probe-failed',3,'https://example.com/');assert(n.status=='degraded')
h.record(n,1120,nil,'probe-failed',3,'https://example.com/');assert(n.status=='down')
h.record(n,1180,200,nil,3,'https://example.com/');assert(n.status=='up' and n.recoveries==1 and n.last_outage==60)
assert(n.last_error==nil and n.events[#n.events].reason=='probe-ok')
local s=h.summary(n);assert(s.measured==3 and math.abs(s.availability-100/3)<.01 and s.p95==200)
h.record(n,1240,nil,'core-offline',3);assert(n.status=='unknown');s=h.summary(n);assert(s.measured==2 and s.unknown==1 and s.availability==50)
for i=1,900 do h.record(n,3600*i,100,nil,3)end;assert(#n.samples==3 and #n.hours==168 and #n.events<=64)
print('Incident recovery, unknown-state exclusion, availability, percentiles and bounded retention passed')
